name = "SoftPredicates"
uuid = "5345b20a-9614-40c4-b281-8f4998fc0f3b"
authors = ["Zenna Tavares"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
